<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="ModelContextProtocol" Version="2.1.0" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
    <PackageVersion Include="SqlParser.Net" Version="1.1.21" />
  </ItemGroup>
</Project>